/**
 * init command - 初始化新项目
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const TEMPLATES = {
  default: {
    'package.json': JSON.stringify({
      name: '{{name}}',
      version: '1.0.0',
      type: 'module',
      main: 'src/index.js',
      scripts: { start: 'node src/index.js', test: 'echo "No tests yet"' },
      license: 'Apache-2.0'
    }, null, 2),
    'src/index.js': `// {{name}} - 入口文件\nconsole.log('Hello from {{name}}!');\n`,
    '.gitignore': 'node_modules/\ndist/\n.env\n*.log\n',
    'README.md': `# {{name}}\n\n> Generated by VBot CLI\n\n## Quick Start\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\`\n`
  }
};

export default async function initCmd(name, options) {
  const projectName = name || 'my-vbot-project';
  const template = TEMPLATES[options.template || 'default'];
  const targetDir = path.resolve(process.cwd(), projectName);

  console.log(`🚀 Initializing project: ${projectName}`);
  console.log(`📁 Target: ${targetDir}`);

  try {
    await fs.mkdir(targetDir, { recursive: true });
  } catch {
    console.error(`❌ Directory ${targetDir} already exists or cannot be created.`);
    process.exit(1);
  }

  for (const [file, content] of Object.entries(template)) {
    const filePath = path.join(targetDir, file.replace('{{name}}', projectName));
    const dir = path.dirname(filePath);
    await fs.mkdir(dir, { recursive: true });
    const fileContent = content.replace(/\{\{name\}\}/g, projectName);
    await fs.writeFile(filePath, fileContent);
    console.log(`  ✓ Created ${file}`);
  }

  console.log('\n✅ Project initialized successfully!');
  console.log(`\n  cd ${projectName}`);
  console.log('  npm install');
  console.log('  npm start\n');
}
